### ISSUE TITLE
utterances가 install되지 않았기 때문에 댓글이 남겨지지 않는 문제가 있습니다.

### ISSUE THREAD

**Issue by johngrib** [shouts77/shouts77.github.io#2]
댓글을 남기려고 하면 다음과 같이 utterances 설치 안내가 나옵니다.

![image](https://user-images.githubusercontent.com/1855714/210588678-a14052d6-16cc-4436-808d-60b6e1e002cc.png)

**Comment by shouts77** [comment]
아.. 집이 있는지도 모르고 손님을 초대했네요.;; 얼른 새 집을 마련하겠습니다. 방문해 주셔서 감사합니다.

**Comment by shouts77** [comment]
repository에 앱을 설치할 수 있다는 걸 처음 알았습니다. utterances 앱을 설치하고 테스트를 아래와 같이 완료했습니다. (곧 giscus로 옮겨갈 예정입니다. ^^)

![스크린샷_20230105_112020](https://user-images.githubusercontent.com/12388981/210686886-1da96b17-0238-40b1-b15a-23e5a060c6ac.png)
